### ISSUE TITLE
Compiling with clang fails

### ISSUE THREAD

**Issue by maribu** [t-lutz/ParallelSTL#15]
Compiling `examples/prime.cpp` with

	clang -I../include -pthread -std=c++14 -o prime prime.cpp

fails with:

	In file included from prime.cpp:5:
	In file included from ../include/experimental/algorithm:7:
	In file included from ../include/experimental/execution_policy:134:
	../include/experimental/bits/parallel/policy_sequential.h:536:3: error: default initialization of an object of const type 'const class sequential_execution_policy' without a user-provided default constructor
	} seq ; //
	  ^
		 {}
	In file included from prime.cpp:5:
	In file included from ../include/experimental/algorithm:7:
	In file included from ../include/experimental/execution_policy:135:
	../include/experimental/bits/parallel/policy_parallel.h:536:3: error: default initialization of an object of const type 'const class parallel_execution_policy' without a user-provided default constructor
	} par ; //
	  ^
		 {}
	In file included from prime.cpp:5:
	In file included from ../include/experimental/algorithm:7:
	In file included from ../include/experimental/execution_policy:135:
	In file included from ../include/experimental/bits/parallel/policy_parallel.h:555:
	../include/experimental/bits/parallel/algos/par/fill_n.h:16:39: error: reference to non-static member function must be called
		  detail::diffract(first, first + count, std::fill<OutputIterator, T>, value);
										  ^~~~~
	../include/experimental/bits/parallel/algos/par/count.h:15:34: note: possible target for call
		  parallel_execution_policy::count(InputIterator first, InputIterator last, 
									 ^
	In file included from prime.cpp:5:
	In file included from ../include/experimental/algorithm:7:
	In file included from ../include/experimental/execution_policy:135:
	In file included from ../include/experimental/bits/parallel/policy_parallel.h:575:
	../include/experimental/bits/parallel/algos/par/max_element.h:18:36: error: reference to non-static member function must be called
									   max_element<ForwardIterator>,
									   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
	../include/experimental/bits/parallel/algos/par/max_element.h:14:48: note: possible target for call
		ForwardIterator parallel_execution_policy::max_element(ForwardIterator first, 
												   ^
	../include/experimental/bits/parallel/policy_parallel.h:460:21: note: possible target for call
		ForwardIterator max_element(ForwardIterator first, ForwardIterator last,
						^
	In file included from prime.cpp:5:
	In file included from ../include/experimental/algorithm:7:
	In file included from ../include/experimental/execution_policy:135:
	In file included from ../include/experimental/bits/parallel/policy_parallel.h:575:
	../include/experimental/bits/parallel/algos/par/max_element.h:28:36: error: reference to non-static member function must be called
									   max_element<ForwardIterator, Compare>,
									   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	../include/experimental/bits/parallel/algos/par/max_element.h:14:48: note: possible target for call
		ForwardIterator parallel_execution_policy::max_element(ForwardIterator first, 
												   ^
	../include/experimental/bits/parallel/algos/par/max_element.h:24:48: note: possible target for call
		ForwardIterator parallel_execution_policy::max_element(ForwardIterator first, 
												   ^
	In file included from prime.cpp:5:
	In file included from ../include/experimental/algorithm:7:
	In file included from ../include/experimental/execution_policy:135:
	In file included from ../include/experimental/bits/parallel/policy_parallel.h:577:
	../include/experimental/bits/parallel/algos/par/min_element.h:18:36: error: reference to non-static member function must be called
									   min_element<ForwardIterator>,
									   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
	../include/experimental/bits/parallel/algos/par/min_element.h:14:48: note: possible target for call
		ForwardIterator parallel_execution_policy::min_element(ForwardIterator first, 
												   ^
	../include/experimental/bits/parallel/policy_parallel.h:452:21: note: possible target for call
		ForwardIterator min_element(ForwardIterator first, ForwardIterator last,
						^
	In file included from prime.cpp:5:
	In file included from ../include/experimental/algorithm:7:
	In file included from ../include/experimental/execution_policy:135:
	In file included from ../include/experimental/bits/parallel/policy_parallel.h:577:
	../include/experimental/bits/parallel/algos/par/min_element.h:28:36: error: reference to non-static member function must be called
									   min_element<ForwardIterator, Compare>,
									   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	../include/experimental/bits/parallel/algos/par/min_element.h:14:48: note: possible target for call
		ForwardIterator parallel_execution_policy::min_element(ForwardIterator first, 
												   ^
	../include/experimental/bits/parallel/algos/par/min_element.h:24:48: note: possible target for call
		ForwardIterator parallel_execution_policy::min_element(ForwardIterator first, 
												   ^
	7 errors generated.

Is support for clang planned/desired?

**Comment by t-lutz** [comment]
Thanks for pointing that you. I haven't touched this repository for a while, it was more of a playground for when we were writing n3554 instead of a fully functional implementation, but I will happily fix those errors if you want to play around with it.
